generic:
  - "passenger car"
  - "sport utility vehicle"
  - "van"
  - "pickup truck"
  - "truck"
  - "bus"
front:
  - "front view of a passenger car"
  - "front view of a sport utility vehicle"
  - "front view of a van or truck"
  - "front view of a bus"
rear:
  - "rear view of a passenger car"
  - "rear view of a sport utility vehicle"
  - "rear view of a van or truck"
  - "rear view of a bus"
side:
  - "side view of a passenger car"
  - "side view of a sport utility vehicle"
  - "side view of a van or truck"
  - "side view of a bus"
